"use client"
import { useState } from "react"
import { Newspaper } from "lucide-react"
import { NEWS_CATEGORIES } from "@/lib/news-service"

interface LandingProps {
  onStart: (category: string) => void
}

const Landing = ({ onStart }: LandingProps) => {
  const [selectedCategory, setSelectedCategory] = useState<string>("general")

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-br from-blue-50 via-white to-blue-100 p-4">
      <div className="bg-white shadow-xl rounded-2xl p-8 max-w-xl w-full flex flex-col items-center">
        <div className="mb-4 bg-blue-100 p-3 rounded-full">
          <Newspaper className="h-10 w-10 text-blue-600" />
        </div>
        <h1 className="text-4xl sm:text-5xl font-extrabold mb-2 text-blue-700 text-center drop-shadow">
          News Made Fun
        </h1>
        <h2 className="text-lg sm:text-xl mb-6 text-center text-blue-500 font-medium">Spot the fake news headline!</h2>
        <p className="text-base sm:text-lg mb-6 text-center text-gray-700 max-w-lg">
          Can you spot the fake news? Test your skills by guessing which headlines are real and which are generated by
          AI. Ready to play?
        </p>

        {/* Category selection */}
        <div className="w-full mb-8">
          <h3 className="text-lg font-medium text-gray-700 mb-3 text-center">Select a news category:</h3>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
            {NEWS_CATEGORIES.map((category) => (
              <button
                key={category.id}
                className={`p-3 rounded-lg border-2 transition-all ${
                  selectedCategory === category.id
                    ? "border-blue-600 bg-blue-50 text-blue-700 font-medium"
                    : "border-gray-200 hover:border-blue-300 hover:bg-blue-50"
                }`}
                onClick={() => setSelectedCategory(category.id)}
                type="button"
              >
                {category.name}
              </button>
            ))}
          </div>
        </div>

        <button
          className="px-8 py-4 bg-blue-600 text-white text-lg font-bold rounded-xl shadow-lg hover:bg-blue-700 transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-offset-2 w-full max-w-xs"
          onClick={() => onStart(selectedCategory)}
        >
          Start Game
        </button>
      </div>
    </div>
  )
}

export default Landing
