import React from 'react';

interface LandingProps {
  onStart: () => void;
}

const Landing = ({ onStart }: LandingProps) => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-50 p-4">
      <h1 className="text-4xl font-bold mb-4 text-center">News Made Fun</h1>
      <p className="text-lg mb-8 text-center text-gray-700 max-w-xl">
        Can you spot the fake news? Test your skills by guessing which headlines are real and which are generated by AI. Ready to play?
      </p>
      <button
        className="px-6 py-3 bg-blue-600 text-white rounded-lg shadow hover:bg-blue-700 transition"
        onClick={onStart}
      >
        Start Game
      </button>
    </div>
  );
};

export default Landing; 